/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application;

import java.awt.event.WindowEvent;

/**
 *
 * @author Karolina
 */
public class NewCustomer extends javax.swing.JFrame {

    private Boolean ok = false;
    
    /**
     * Creates new form NewCustomer
     */
    public NewCustomer() {
        initComponents();
        this.setVisible(true);
    }
    
    public String getFirstname() {
        return this.jfirstnm_txt.getText();
    }
    public String getLastname() {
        return this.jlastnm_txt.getText();
    }
    public String getDob() {
        return this.jdob_txt.getText();
    }
    public String getMail() {
        return this.jmail_txt.getText();
    }
    public String getPW() {
        return this.jpasswd_txt.getText();
    }
    
    public Boolean getOK() {
        return this.ok;
    }
    
    public String getStreet() {
        return this.jstreet_txt.getText();
    }
    public String getHousenr() {
        return this.jhousenr_txt.getText();
    }
    public String getZip() {
        return this.jzip_txt.getText();
    }
    public String getCity() {
        return this.jcity_txt.getText();
    }
    public String getCountry() {
        return this.jcountry_txt.getText();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jfirstnm = new javax.swing.JLabel();
        jlastnm = new javax.swing.JLabel();
        jdob = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jstreet = new javax.swing.JLabel();
        jzip = new javax.swing.JLabel();
        jcity = new javax.swing.JLabel();
        jcountry = new javax.swing.JLabel();
        jhousenr = new javax.swing.JLabel();
        jstreet_txt = new javax.swing.JTextField();
        jhousenr_txt = new javax.swing.JTextField();
        jzip_txt = new javax.swing.JTextField();
        jcity_txt = new javax.swing.JTextField();
        jcountry_txt = new javax.swing.JTextField();
        jfirstnm_txt = new javax.swing.JTextField();
        jlastnm_txt = new javax.swing.JTextField();
        jdob_txt = new javax.swing.JTextField();
        jbtnsend = new javax.swing.JButton();
        jmail = new javax.swing.JLabel();
        jpasswd = new javax.swing.JLabel();
        jpasswd_txt = new javax.swing.JTextField();
        jmail_txt = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("New customer");

        jfirstnm.setText("Firstname");

        jlastnm.setText("Lastname");

        jdob.setText("Date of birth");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Address");

        jstreet.setText("Street");

        jzip.setText("Zip");

        jcity.setText("City");

        jcountry.setText("Country");

        jhousenr.setText("House number");

        jstreet_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jstreet_txtActionPerformed(evt);
            }
        });

        jhousenr_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhousenr_txtActionPerformed(evt);
            }
        });

        jzip_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jzip_txtActionPerformed(evt);
            }
        });

        jcity_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcity_txtActionPerformed(evt);
            }
        });

        jcountry_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcountry_txtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jstreet)
                                .addGap(76, 76, 76)
                                .addComponent(jstreet_txt))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcity)
                                .addGap(87, 87, 87)
                                .addComponent(jcity_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcountry)
                                .addGap(67, 67, 67)
                                .addComponent(jcountry_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jhousenr)
                                        .addGap(37, 37, 37)
                                        .addComponent(jhousenr_txt))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jzip)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jzip_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(119, 119, 119)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jstreet)
                    .addComponent(jstreet_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jhousenr)
                    .addComponent(jhousenr_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jzip)
                    .addComponent(jzip_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcity)
                    .addComponent(jcity_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcountry)
                    .addComponent(jcountry_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jfirstnm_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfirstnm_txtActionPerformed(evt);
            }
        });

        jbtnsend.setText("Send");
        jbtnsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsendActionPerformed(evt);
            }
        });

        jmail.setText("E-Mail");

        jpasswd.setText("Password");

        jmail_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmail_txtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdob)
                    .addComponent(jlastnm)
                    .addComponent(jfirstnm)
                    .addComponent(jmail)
                    .addComponent(jpasswd))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jfirstnm_txt)
                    .addComponent(jlastnm_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(jdob_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmail_txt)
                    .addComponent(jpasswd_txt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnsend)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfirstnm)
                    .addComponent(jfirstnm_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlastnm)
                    .addComponent(jlastnm_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdob)
                    .addComponent(jdob_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jmail)
                    .addComponent(jmail_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpasswd)
                    .addComponent(jpasswd_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnsend)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jfirstnm_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfirstnm_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfirstnm_txtActionPerformed

    private void jstreet_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jstreet_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jstreet_txtActionPerformed

    private void jhousenr_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhousenr_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jhousenr_txtActionPerformed

    private void jzip_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jzip_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jzip_txtActionPerformed

    private void jcity_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcity_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcity_txtActionPerformed

    private void jcountry_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcountry_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcountry_txtActionPerformed

    private void jbtnsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsendActionPerformed
        // TODO add your handling code here:
        System.out.println("Do Something Clicked");
        this.ok = true;
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jbtnsendActionPerformed

    private void jmail_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmail_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmail_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaujfirstnm="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnsend;
    private javax.swing.JLabel jcity;
    private javax.swing.JTextField jcity_txt;
    private javax.swing.JLabel jcountry;
    private javax.swing.JTextField jcountry_txt;
    private javax.swing.JLabel jdob;
    private javax.swing.JTextField jdob_txt;
    private javax.swing.JLabel jfirstnm;
    private javax.swing.JTextField jfirstnm_txt;
    private javax.swing.JLabel jhousenr;
    private javax.swing.JTextField jhousenr_txt;
    private javax.swing.JLabel jlastnm;
    private javax.swing.JTextField jlastnm_txt;
    private javax.swing.JLabel jmail;
    private javax.swing.JTextField jmail_txt;
    private javax.swing.JLabel jpasswd;
    private javax.swing.JTextField jpasswd_txt;
    private javax.swing.JLabel jstreet;
    private javax.swing.JTextField jstreet_txt;
    private javax.swing.JLabel jzip;
    private javax.swing.JTextField jzip_txt;
    // End of variables declaration//GEN-END:variables
}
